"""
This module contains the constants used for importing from the JSON from the API response from calling the scheduling
API.
"""
BEGIN_TIME = "beginTime"
COURSE_TITLE = "courseTitle"
COURSE_NUMBER = "courseNumber"
DATA = "data"
DAYS_BOOKED = "days_booked"
DAY_0 = "sunday"
DAY_1 = "monday"
DAY_2 = "tuesday"
DAY_3 = "wednesday"
DAY_4 = "thursday"
DAY_5 = "friday"
DAY_6 = "saturday"
END_TIME = "endTime"
ID = "id"
MEETINGS_FACULTY = "meetingsFaculty"
MEETING_TIME = "meetingTime"
ROOM = "room"
SEQUENCE_NUMBER = "sequenceNumber"
SCHEDULE_TYPE_DESCRIPTION = "scheduleTypeDescription"
SUBJECT = "subject"
SUBJECT_DESCRIPTION = "subjectDescription"
